#!/bin/bash

USER="docker"
PASS="docker"
DB="docker"
TEMPLATE="DEFAULT"

POSTGRESQL_USER=${POSTGRESQL_USER:-$USER}
POSTGRESQL_PASS=${POSTGRESQL_PASS:-$PASS}
POSTGRESQL_DB=${POSTGRESQL_DB:-$DB}
POSTGRESQL_TEMPLATE=${POSTGRESQL_TEMPLATE:-$TEMPLATE}